### ISSUE TITLE
Extract Literal attribute ? 

### ISSUE THREAD

**Issue by ignatandrei** [feast107/CodeAnalysis#1]
I do like your idea of Literal Attribute - convert text into string. I did put into the collection of my Roslyn Source Code Generators -  https://ignatandrei.github.io/RSCG_Examples/v2/docs/CodeAnalysis

However, it comes with a lot of other generated files. Could you extract into a new package ?

**Comment by feast107** [comment]
Actually, I already did it in my code,  using Shared Project. (It's really useful !). I didnt package it bcs it was just me who use it. I'll extract and pack it soon as possibile.

**Comment by feast107** [comment]
I'v published on nuget : [`Feast.CodeAnalysis.Literal`](https://www.nuget.org/packages/Feast.CodeAnalysis.Literal/)
And make the latest version of `Feast.CodeAnalysis` depends on it

**Comment by ignatandrei** [comment]
Thanks! Modified !
